# Generated by Django 3.1.5 on 2021-01-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('gmail', models.CharField(blank=True, max_length=50, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('max_fetch', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_data', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Stats',
                'managed': False,
            },
        ),
    ]
